### ISSUE TITLE
画像リソースについて ETag による適切なクライアントサイドキャッシュを導入する

### ISSUE THREAD

**Issue by supermomonga** [pgrho/animedb#3]
# 問題

`EpisodeController` の `Thumbnail` メソッドについて、画像の内容が変わった場合も ETag によるチェックが働いておらず、ブラウザがキャッシュを破棄しない

# 提案

ETag は url 単位でユニークであれば良いので、ETag はエピソードの `ThumbnailUpdatedAt` プロパティ値の文字列表現（もしくはそれから生成したハッシュ値）を採用するようにし、`Thumbnail` メソッドにはリクエストヘッダー内の ETag （`Request.Headers["If-None-Match"]`）をチェックし、返して良い場合のみ `304 Not Modified` を返す様な処理を入れる

また、もし現状 IIS のレイヤで勝手に `304 Not Modified` を返却しているのであれば、アプリケーション層で面倒を見るように変更する

**Comment by pgrho** [comment]
手抜きがバレてしまったか…

**Comment by pgrho** [comment]
Series, Season, EpisodeのサムネsrcをThumbnailIdベースに変更
→URL自体が変化するのでキャッシュ有効期限の問題はないはず
304判定をLast-Modified/ETagの併用に変更
